import { describe, expect, test, beforeEach } from "bun:test";
import { isTauriEnv } from "./index";
import { mockBridge } from "./mock";
import { Session, Message } from "./types";

// --- Mock localStorage for CLI Test Environment ---
if (typeof globalThis.localStorage === "undefined") {
  const store: Record<string, string> = {};
  globalThis.localStorage = {
    getItem: (key: string) => store[key] || null,
    setItem: (key: string, value: string) => {
      store[key] = value;
    },
    removeItem: (key: string) => {
      delete store[key];
    },
    clear: () => {
      for (const k in store) delete store[k];
    },
    key: (index: number) => Object.keys(store)[index] || null,
    length: 0,
  };
  Object.defineProperty(globalThis.localStorage, "length", {
    get: () => Object.keys(store).length,
  });
}

// --- Mock window for CLI Test Environment ---
if (typeof globalThis.window === "undefined") {
  globalThis.window = {
    __TAURI_INTERNALS__: undefined,
  } as any;
}

describe("JS Bridge - Environment Detection", () => {
  test("should detect non-tauri env by default in test runner", () => {
    expect(isTauriEnv()).toBe(false);
  });

  test("should detect tauri env when internals exist", () => {
    // Setup window mock
    const originalInternals = window.__TAURI_INTERNALS__;
    window.__TAURI_INTERNALS__ = {};
    
    expect(isTauriEnv()).toBe(true);

    // Cleanup
    window.__TAURI_INTERNALS__ = originalInternals;
  });
});

describe("JS Bridge - Mock Fallback APIs", () => {
  beforeEach(() => {
    localStorage.clear();
  });

  test("greet() should return browser mock greeting", async () => {
    const result = await mockBridge.greet("John");
    expect(result).toBe("Hello, John! You've been greeted from Browser Mock!");
  });

  test("checkForUpdates() should return mock updates info", async () => {
    const update = await mockBridge.checkForUpdates();
    expect(update.hasUpdate).toBe(true);
    expect(update.version).toBe("0.3.0");
  });

  test("installUpdate() should report download progress", async () => {
    const progressLog: number[] = [];
    await mockBridge.installUpdate((status) => {
      if (status.status === "downloading" && status.progress !== undefined) {
        progressLog.push(status.progress);
      }
    });
    expect(progressLog.length).toBeGreaterThanOrEqual(1);
    // 最终进度应该到达 100
    const lastProgress = progressLog[progressLog.length - 1];
    expect(lastProgress).toBe(50); // mock 只模拟到 50%
  });

  test("installUpdate() pauses at 'downloaded' and does NOT auto-install (v0.5.2 two-phase)", async () => {
    let lastStatus: string | undefined;
    await mockBridge.installUpdate((status) => {
      lastStatus = status.status;
    });
    expect(lastStatus).toBe("downloaded");
  });

  test("confirmUpdateInstall() returns user choice (mock uses window.confirm)", async () => {
    const originalConfirm = window.confirm;
    try {
      window.confirm = () => true;
      expect(await mockBridge.confirmUpdateInstall("0.5.2")).toBe(true);
      window.confirm = () => false;
      expect(await mockBridge.confirmUpdateInstall("0.5.2")).toBe(false);
    } finally {
      window.confirm = originalConfirm;
    }
  });

  test("installDownloadedUpdate() is a no-op in mock environment", async () => {
    await expect(mockBridge.installDownloadedUpdate()).resolves.toBeUndefined();
  });

  test("session ID should start with 'ses_' for opencode compatibility", () => {
    // opencode's SessionV2.ID.make() requires IDs to start with "ses"
    // This test validates the session ID format generated by the app
    const id = "ses_" + crypto.randomUUID();
    expect(id).toMatch(/^ses_/);
    expect(id.length).toBeGreaterThan(4);

    // 验证 opencode 兼容性: "ses_" 前缀 + UUID 不包含空格或特殊字符
    const parts = id.split("_");
    expect(parts[0]).toBe("ses");
    expect(parts[1]).toBeDefined();
    expect(/^[0-9a-f-]+$/.test(parts[1])).toBe(true);
  });

  test("runAgent should accept agentMode parameter and forward it", async () => {
    // 验证 agentMode 参数能被正确传递 (mock bridge 记录日志但不执行)
    const events: any[] = [];
    await mockBridge.runAgent("test-key", "test-model", [], ".", "ses_test-id", undefined, (e) => events.push(e));
    expect(events.length).toBeGreaterThan(0);

    // 带 plan mode 调用
    const planEvents: any[] = [];
    await mockBridge.runAgent("test-key", "test-model", [], ".", "ses_test-id", "plan", (e) => planEvents.push(e));
    expect(planEvents.length).toBeGreaterThan(0);
  });

  test("agentMode 'plan' should be passed through bridge layer", () => {
    // 验证 tauri bridge 中 runAgent 的正确参数格式
    // (这个测试确保 agentMode 参数签名正确，实际 invoke 在 mock 环境不可用)
    const agentMode: string | undefined = "plan";
    expect(typeof agentMode).toBe("string");
    expect(agentMode).toBe("plan");

    const nullMode: string | undefined = undefined;
    expect(nullMode).toBeUndefined();
  });

  test("selectDirectory() should return mock folder path", async () => {
    const originalPrompt = window.prompt;
    window.prompt = () => "/mock/path";
    const dir = await mockBridge.selectDirectory();
    expect(dir).toBe("/mock/path");
    window.prompt = originalPrompt;
  });

  test("initDb() should initialize empty sessions in localStorage", async () => {
    await mockBridge.initDb();
    const sessionsJson = localStorage.getItem("bridge_mock_sessions");
    const messagesJson = localStorage.getItem("bridge_mock_messages");
    
    expect(sessionsJson).toBe("[]");
    expect(messagesJson).toBe("[]");
  });

  test("saveSession() & getSessions() should insert and sort sessions", async () => {
    await mockBridge.initDb();

    const session1: Session = {
      id: "session-1",
      title: "First Session",
      lastMessage: "hello",
      updatedAt: new Date("2026-06-05T10:00:00Z").toISOString(),
      projectName: "deepseek-code",
    };

    const session2: Session = {
      id: "session-2",
      title: "Second Session",
      lastMessage: "world",
      updatedAt: new Date("2026-06-05T11:00:00Z").toISOString(), // Newer date
      projectName: "deepseek-code",
    };

    await mockBridge.saveSession(session1);
    await mockBridge.saveSession(session2);

    const sessions = await mockBridge.getSessions();
    expect(sessions.length).toBe(2);
    // session2 should be first because of newer updatedAt timestamp
    expect(sessions[0].id).toBe("session-2");
    expect(sessions[1].id).toBe("session-1");
  });

  test("saveMessage() & getMessages() should handle message lists", async () => {
    await mockBridge.initDb();

    const msg: Message = {
      id: "msg-1",
      sessionId: "session-1",
      role: "user",
      content: "Hi Agent",
      createdAt: new Date().toISOString(),
    };

    await mockBridge.saveMessage(msg);

    const msgs = await mockBridge.getMessages("session-1");
    expect(msgs.length).toBe(1);
    expect(msgs[0].content).toBe("Hi Agent");
    expect(msgs[0].role).toBe("user");
  });

  test("deleteSession() should delete session and cascade delete messages", async () => {
    await mockBridge.initDb();

    const session: Session = {
      id: "session-1",
      title: "To Delete",
      lastMessage: "bye",
      updatedAt: new Date().toISOString(),
    };

    const msg: Message = {
      id: "msg-1",
      sessionId: "session-1",
      role: "user",
      content: "Bye Agent",
      createdAt: new Date().toISOString(),
    };

    await mockBridge.saveSession(session);
    await mockBridge.saveMessage(msg);

    // Ensure they exist
    expect((await mockBridge.getSessions()).length).toBe(1);
    expect((await mockBridge.getMessages("session-1")).length).toBe(1);

    // Delete
    await mockBridge.deleteSession("session-1");

    // Verify deletion
    expect((await mockBridge.getSessions()).length).toBe(0);
    expect((await mockBridge.getMessages("session-1")).length).toBe(0);
  });

  test("saveSetting(), getSetting(), deleteSetting() should manage configuration settings", async () => {
    const initial = await mockBridge.getSetting("test_key");
    expect(initial).toBeNull();

    await mockBridge.saveSetting("test_key", "test_value");
    const val = await mockBridge.getSetting("test_key");
    expect(val).toBe("test_value");

    await mockBridge.deleteSetting("test_key");
    const deleted = await mockBridge.getSetting("test_key");
    expect(deleted).toBeNull();
  });
});

